en:
  languageName: English
  contentDir: content/en
  weight: 2
  ### copyright (markdown can be used) ###
  copyright: "Copyright &copy; {{< current_year >}} The Neetpiq Lab. All Rights Reserved. [Dot Org Theme](https://github.com/cncf/dot-org-hugo-theme) for Hugo by [CNCF](https://www.cncf.io)."
  title: "The Neetpiq Lab"
  params:
    description: "Space for experiments in the software world, between homelabs, devops and small projects with IoT devices and a touch of 3D printing when needed to give shape to ideas."
    ### accessibility ###
    accessibility:
      skip_text: "Skip to content"
      help_text: "Accessibility Statement"
      help_url: ""
    ### calls to action ###
    main_cta:
      text: ""
      link: "/example-page/"
    footer_cta:
      text: ""
      link: "/example-page/"
    github_edit: "Edit this page on GitHub"
  ### example menu showing children ###
  menu:
    main:
    - identifier: "blog"
      name: "Blog"
      url: "/blog/"
      weight: 1
    - identifier: "demo-page"
      name: "Menu"
      #url: "/demo-page/"
      weight: 2
    - identifier: "child-1"
      name: "Example Child Page"
      url: "/example-page/"
      weight: 1
      post: "Nulla consequat massa quis enim. Donec pede justo."
      parent: "demo-page"
    - identifier: "child-2"
      name: "Example Child Page"
      url: "/example-page/"
      weight: 2
      post: "Aenean commodo ligula get dolor. Aenean massa."
      parent: "demo-page"
    - identifier: "about"
      name: "About"
      url: "/about-page/"
      weight: 3
    - identifier: "faq"
      name: "FAQs"
      url: "/faq/"
      weight: 4
    
it:
  languageName: Italiano
  # contentDir: content/it
  weight: 1
  title: "The Neetpiq Lab"
  copyright: "Copyright &copy; 2003-{{< current_year >}} The Neetpiq Lab. All Rights Reserved. [Dot Org Theme](https://github.com/cncf/dot-org-hugo-theme) for Hugo by [CNCF](https://www.cncf.io)."
  params:
    description: "Spazio per esperimenti nel mondo software, tra homelab, devops e progetti con dispositivi IoT."
  menu:
    main:
    - identifier: "blog"
      name: "Blog"
      url: "/blog/"
      weight: 1
    - identifier: "demo-page"
      name: "Menu"
      #url: "/demo-page/"
      weight: 2
    - identifier: "child-1"
      name: "Example Child Page"
      url: "/example-page/"
      weight: 1
      post: "Pagina di esempio"
      parent: "demo-page"
    - identifier: "child-2"
      name: "Demo Page"
      url: "/demo-page/"
      weight: 2
      post: "Pagina demo"
      parent: "demo-page"
    - identifier: "about"
      name: "Infos"
      url: "/about-page/"
      weight: 3
    - identifier: "faq"
      name: "FAQs"
      url: "/faq/"
      weight: 4
    
